/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controladores.ControladorArtista;
import Modelos.Discografia;

/**
 *
 * @author Alumno
 */
public class AltaArtistaPanel extends javax.swing.JPanel {
    
    public AltaArtistaPanel() {
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nombreArtista = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cantidadIntegrantes = new javax.swing.JTextField();
        consagrado = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        generoMusical = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        agregarArtista = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(551, 428));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nombre:");

        nombreArtista.setText("Ej: Los Pepitos");
        nombreArtista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreArtistaActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Cantidad de Integrantes:");

        cantidadIntegrantes.setText("Ej: 3");

        consagrado.setForeground(new java.awt.Color(0, 0, 0));
        consagrado.setText("Consagrado");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Genero Musical:");

        generoMusical.setText("Ej: Rock Nacional");
        generoMusical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generoMusicalActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Agregar Artista");

        agregarArtista.setBackground(new java.awt.Color(0, 255, 0));
        agregarArtista.setText("Agregar");
        agregarArtista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarArtistaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(agregarArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(165, 165, 165)
                            .addComponent(jLabel4))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(38, 38, 38)
                            .addComponent(jLabel1)
                            .addGap(102, 102, 102)
                            .addComponent(nombreArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(38, 38, 38)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(cantidadIntegrantes, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(38, 38, 38)
                            .addComponent(jLabel3)
                            .addGap(60, 60, 60)
                            .addComponent(generoMusical, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(38, 38, 38)
                            .addComponent(consagrado))))
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel4)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1))
                    .addComponent(nombreArtista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cantidadIntegrantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(generoMusical, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(consagrado)
                .addGap(47, 47, 47)
                .addComponent(agregarArtista)
                .addContainerGap(25, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void agregarArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarArtistaActionPerformed
       ControladorArtista controladora = new ControladorArtista(); 
        String Nombre = getNombreArtista();
       int cant = getCantidadIntegrantes();
       String genero = getGeneroMusical();
       boolean consagrado = getConsagrado();
       controladora.nuevoArtista(Nombre, cant, genero, consagrado);
    }//GEN-LAST:event_agregarArtistaActionPerformed

    private void nombreArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreArtistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreArtistaActionPerformed

    private void generoMusicalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generoMusicalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_generoMusicalActionPerformed

    public String getNombreArtista(){
        return nombreArtista.getText();
    }
    
    public int getCantidadIntegrantes(){
        int numIntegrantes = Integer.parseInt(cantidadIntegrantes.getText());
        return numIntegrantes;
    }
    
    public String getGeneroMusical(){
        return generoMusical.getText();
    }
    
    public boolean getConsagrado(){
        return consagrado.isSelected();
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarArtista;
    private javax.swing.JTextField cantidadIntegrantes;
    private javax.swing.JCheckBox consagrado;
    private javax.swing.JTextField generoMusical;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField nombreArtista;
    // End of variables declaration//GEN-END:variables
}
