/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controladores.ControladorCancion;

/**
 *
 * @author Usuario PC
 */
public class AltaCancionPanel extends javax.swing.JPanel {

    /**
     * Creates new form AltaCancionPanel
     */
    public AltaCancionPanel() {
        initComponents();
    }
    
    
    public String getNombre(){
        return NombreFild.getText();
    }
    
    public String getOwner(){
        return OwnerFild.getText().toUpperCase();
    }
    
    public int getDisco(){
        int disco = Integer.parseInt(DiscoFild.getText());
        return disco;
    }
    
    public int getDuracion(){
        int Duracion = Integer.parseInt(DuracionFild.getText());
        return Duracion;
    }
    
    public int getReproducciones(){
        int rep = Integer.parseInt(ReproduccionesFild.getText());
        return rep;
    }
    
    public boolean getSencillo(){
        return SencilloCheck.isSelected();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        AgreggarCancionBTN = new javax.swing.JButton();
        NombreFild = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        DuracionFild = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        OwnerFild = new javax.swing.JTextField();
        SencilloCheck = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        ReproduccionesFild = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        DiscoFild = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nueva Cancion");

        AgreggarCancionBTN.setText("Agregar");
        AgreggarCancionBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgreggarCancionBTNActionPerformed(evt);
            }
        });

        NombreFild.setText("Ej: De musica ligera");
        NombreFild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreFildActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre:");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Duracion:  (Seg)");

        DuracionFild.setText("Ej: 84");
        DuracionFild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DuracionFildActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Owner: (codigo de Artista)");

        OwnerFild.setText("Ej: AAAAAA");
        OwnerFild.setToolTipText("puto");

        SencilloCheck.setText("Sencillo");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Reproducciones");

        ReproduccionesFild.setText("Ej: 9999");

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Disco:");

        DiscoFild.setText("Ej: 1");
        DiscoFild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiscoFildActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DuracionFild, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(DiscoFild, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(OwnerFild, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(54, 54, 54)
                                        .addComponent(AgreggarCancionBTN)
                                        .addGap(50, 50, 50)
                                        .addComponent(SencilloCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(NombreFild, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(ReproduccionesFild, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(NombreFild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(ReproduccionesFild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(DuracionFild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(DiscoFild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(OwnerFild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SencilloCheck)
                    .addComponent(AgreggarCancionBTN))
                .addContainerGap(62, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void NombreFildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreFildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreFildActionPerformed

    private void DuracionFildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DuracionFildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DuracionFildActionPerformed

    private void AgreggarCancionBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgreggarCancionBTNActionPerformed
        ControladorCancion Controlador = new ControladorCancion();
        Controlador.nuevaCancion(getOwner(),getNombre(),getDuracion(),getReproducciones(),getDisco(), getSencillo());
    }//GEN-LAST:event_AgreggarCancionBTNActionPerformed

    private void DiscoFildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiscoFildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DiscoFildActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgreggarCancionBTN;
    private javax.swing.JTextField DiscoFild;
    private javax.swing.JTextField DuracionFild;
    private javax.swing.JTextField NombreFild;
    private javax.swing.JTextField OwnerFild;
    private javax.swing.JTextField ReproduccionesFild;
    private javax.swing.JCheckBox SencilloCheck;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
