/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controladores.ControladorArtista;
import Controladores.ControladorCancion;
import Modelos.Artista;
import Modelos.Cancion;
import java.awt.BorderLayout;
import java.util.ArrayList;
import java.util.TreeMap;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario PC
 */
public class CancionesPanel extends javax.swing.JPanel {

    /**
     * Creates new form CancionesPanel
     */
    public CancionesPanel() {
        initComponents();
        this.setVisible(true);
    }
    public void MostrarLista() {  
        TreeMap<Integer,Cancion> canciones;
        ControladorCancion control = new ControladorCancion();
        DefaultTableModel model = new DefaultTableModel();
        
        canciones = control.getCanciones();
        
        model.addColumn("Nombre");
        model.addColumn("Duracion");
        model.addColumn("Reproducciones");
        model.addColumn("Tipo");
        model.addColumn("Owner");
        TablaArtistas.setModel(model);
        
        model.setRowCount(0);
        for (Cancion act:canciones.values()) {
            
                Object[] fila = {
                    act.getNombre(),
                    act.getDuracion(),
                    act.getReproducciones(),
                    act.getTipo(),
                    act.getOwner()
                };
                System.out.println(act);
                model.addRow(fila);
        }
    }
    
    public void setBackground(JPanel panel) {
       
       panel.setSize(500,500);
       panel.setLocation(0,0);
       bodyPanel.removeAll();
       bodyPanel.add(panel, BorderLayout.CENTER);
       bodyPanel.revalidate();
       bodyPanel.repaint(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bodyPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaArtistas = new javax.swing.JTable();
        BTNPanel = new javax.swing.JPanel();
        EliminarArtistaBTN = new javax.swing.JButton();
        AgregarArtistaBTN = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 102, 102));

        bodyPanel.setBackground(new java.awt.Color(255, 255, 255));
        bodyPanel.setPreferredSize(new java.awt.Dimension(456, 481));

        TablaArtistas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaArtistas);

        javax.swing.GroupLayout bodyPanelLayout = new javax.swing.GroupLayout(bodyPanel);
        bodyPanel.setLayout(bodyPanelLayout);
        bodyPanelLayout.setHorizontalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        bodyPanelLayout.setVerticalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
        );

        BTNPanel.setBackground(new java.awt.Color(0, 153, 204));
        BTNPanel.setForeground(new java.awt.Color(255, 255, 255));
        BTNPanel.setPreferredSize(new java.awt.Dimension(375, 136));

        EliminarArtistaBTN.setBackground(new java.awt.Color(255, 0, 0));
        EliminarArtistaBTN.setText("Eliminar Cancion");

        AgregarArtistaBTN.setBackground(new java.awt.Color(51, 255, 0));
        AgregarArtistaBTN.setText("Nueva Cancion");
        AgregarArtistaBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarArtistaBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BTNPanelLayout = new javax.swing.GroupLayout(BTNPanel);
        BTNPanel.setLayout(BTNPanelLayout);
        BTNPanelLayout.setHorizontalGroup(
            BTNPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BTNPanelLayout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(AgregarArtistaBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 203, Short.MAX_VALUE)
                .addComponent(EliminarArtistaBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146))
        );
        BTNPanelLayout.setVerticalGroup(
            BTNPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BTNPanelLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(BTNPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgregarArtistaBTN)
                    .addComponent(EliminarArtistaBTN))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BTNPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 831, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 819, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTNPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarArtistaBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarArtistaBTNActionPerformed
        AltaCancionPanel panel = new AltaCancionPanel();
        setBackground(panel);

    }//GEN-LAST:event_AgregarArtistaBTNActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarArtistaBTN;
    private javax.swing.JPanel BTNPanel;
    private javax.swing.JButton EliminarArtistaBTN;
    private javax.swing.JTable TablaArtistas;
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
