/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;
import java.awt.event.ActionListener;
import javax.swing.*;

/**
 *
 * @author Usuario PC
 */
public class FormularioArtista extends javax.swing.JPanel {

    /**
     * Creates new form FormularioArtista
     */
    public FormularioArtista() {
        initComponents();
        CrearArtista.setActionCommand("Crear");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CheckConsagrado = new javax.swing.JRadioButton();
        CrearArtista = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        nombreArtista = new javax.swing.JTextField();

        CheckConsagrado.setText("jRadioButton1");
        CheckConsagrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckConsagradoActionPerformed(evt);
            }
        });

        CrearArtista.setText("jButton1");
        CrearArtista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearArtistaActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        nombreArtista.setText("jTextField1");
        nombreArtista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreArtistaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(207, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CrearArtista)
                    .addComponent(CheckConsagrado))
                .addGap(100, 100, 100))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addGap(54, 54, 54)
                .addComponent(nombreArtista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nombreArtista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(CheckConsagrado)
                .addGap(44, 44, 44)
                .addComponent(CrearArtista)
                .addGap(41, 41, 41))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void setActionListener(ActionListener controlador){
        CrearArtista.addActionListener(controlador);
    }
    public String getNombre(){
        return nombreArtista.getText();
    }
    public Boolean getConsagrado(){
        return consagrado.isSelected();
    } 
    
    public int getCantidadIntegrantes(){
        return cantidadIntegrantes.getText();
    }
    
    private void CheckConsagradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckConsagradoActionPerformed
        
    }//GEN-LAST:event_CheckConsagradoActionPerformed

    private void CrearArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearArtistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CrearArtistaActionPerformed

    private void nombreArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreArtistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreArtistaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JRadioButton CheckConsagrado;
    public javax.swing.JButton CrearArtista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nombreArtista;
    // End of variables declaration//GEN-END:variables
}
