/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.awt.event.ActionListener;

/**
 *
 * @author Alumno
 */
public class FormularioArtista extends javax.swing.JPanel {

    /**
     * Creates new form FormularioArtista
     */
    public FormularioArtista() {
        initComponents();
        agregarArtista.setActionCommand("Crear");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nombreArtista = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cantidadIntegrantes = new javax.swing.JTextField();
        consagrado = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        generoMusical = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        agregarArtista = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(551, 428));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        nombreArtista.setText("Los Pepitos");
        add(nombreArtista, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 116, -1));

        jLabel2.setText("Cantidad de Integrantes:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 129, 20));

        cantidadIntegrantes.setText("3");
        add(cantidadIntegrantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 40, 20));

        consagrado.setText("Consagrado");
        add(consagrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 195, -1, -1));

        jLabel3.setText("Genero Musical:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        generoMusical.setText("Rock Nacional");
        add(generoMusical, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 116, -1));

        jLabel4.setText("Agregar Artista");
        jLabel4.setBorder(new javax.swing.border.MatteBorder(null));
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        agregarArtista.setText("Agregar");
        add(agregarArtista, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 78, -1));
    }// </editor-fold>//GEN-END:initComponents

    
    public void setActionListener(ActionListener controlador){
        agregarArtista.addActionListener(controlador);
    }
    
    public String getNombreArtista(){
        return nombreArtista.getText();
    }
    
    public int getCantidadIntegrantes(){
        int numIntegrantes = Integer.parseInt(cantidadIntegrantes.getText());
        return numIntegrantes;
    }
    
    public String getGeneroMusical(){
        return generoMusical.getText();
    }
    
    public boolean getConsagrado(){
        return consagrado.isSelected();
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarArtista;
    private javax.swing.JTextField cantidadIntegrantes;
    private javax.swing.JCheckBox consagrado;
    private javax.swing.JTextField generoMusical;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField nombreArtista;
    // End of variables declaration//GEN-END:variables
}
